apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  labels:
    app: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: maps-server
        image: rylanm14/proj-map-server:latest
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: '6379'
        - name: MINIO_HOST
          value: "minio:9000"
        ports:
        - containerPort: 3000
        - containerPort: 6379
        - containerPort: 9000