apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socket
  annotations:
    nginx.ingress.kubernetes.io/enable-websockets: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /socket
        pathType: Prefix
        backend:
          service:
            name: socket
            port:
              number: 80
