apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
    spec:
      containers:
      - name: socket
        image: ibrhmch/socket:latest
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: PSQL_HOST
          value: "postgres"
        - name: PSQL_PORT
          value: "5432"
        - name: SERVER_PORT
          value: "5000"
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
